### ISSUE TITLE
[Feature request] Refresh File

### ISSUE THREAD

**Issue by AaronB2019** [JasonStein/Notepads#1063]
**Is your feature request related to a problem? Please describe.**
The problem is the when the file is externally modified, there is no way to refresh to get the most updated information. Currently, notepads would just inform that the file has been externally modified and user can only reopen the file which is annoying. For example, when modifying it through certain codes.

**Describe the solution you'd like**
The solution would be similar to notepad++. When the file is externally modified. There will be pop up menu that asks the user if you would like to reload the text file. 

**Describe alternatives you've considered**
Another solution would probably just be having a shortcut key to refresh the file such as CTRL + R.

Thank you for your time.

**Comment by JasonStein** [comment]
Click on the file path and here you go:
![image](https://user-images.githubusercontent.com/1166162/159439445-eda26331-0c2d-44dc-b1fc-a5bcb675bc13.png)

The reason I am not forcing a pop-up window is simply because it is too annoying. As you already see, Notepads will notify you for the external edit. If you want to reload, just click the button in the above screenshot. Or Ctrl+Shift+R.

**Comment by AaronB2019** [comment]
Oh wow! I didn't know you could click on the path! Yes, I agree that the pop up window is so super annoying. This is much better especially with a hotkey! I didn't know the bottom right texts can be clicked too! Amazing! Thank you so much for your time!
