### ISSUE TITLE
[Feature request]Double Font

### ISSUE THREAD

**Issue by TXFK** [JasonStein/Notepads#1076]
# The second font is useful.
For example, some Chinese Font don't have a good support in the Western characters such as `Source Han Serif CN(思源宋体)`. If I am going to get a better visual experience, a Double Font Feature is very important.
**As well, thanks for your developing. It's really fantastic and I feel better when I'm reading logs.    : )**

**Comment by JasonStein** [comment]
There is no plan to add fallback font support since it is too complex and triky since you need to define what characters are "fallbackable". However, what you can do is, you can merge two .ttf or other type of font files into one using online tools or your own to create one single font file to be consumed by Notepads. When merging the two, you can choose a subset of characters to use for each original font asset. In your case, that would be 'a'-'z', 'A'-'Z' and 0-9 etc..
