### ISSUE TITLE
[Bug] Notepads window can't be moved when settings is open

### ISSUE THREAD

**Issue by Tarik02** [JasonStein/Notepads#116]
**Describe the bug**
Notepads window can't be moved when settings is open.

**To Reproduce**
1. Put Notepads to the middle of the screen.
2. Open Notepads settings.
3. Try to move the window.

**Expected behavior**
I can move the window

**Desktop (please complete the following information):**
 - OS: Windows 10 1903 (build 18362.116)
 - Version: https://github.com/JasonStein/Notepads/commit/1ac5d5a7cd7ea6197418830dbb84581f385d7b1e

**Comment by JasonStein** [comment]
I probably will not fix this since there is no close button for settings and I am expecting user to click on anywhere outside settings to close settings panel. On the other hand, there is no real need for anyone to move window while settings panel is opened. User can always close settings first. What's more, settings in this app is not something user will frequently interact with. So conclusion would be keep as it is for now.
