### ISSUE TITLE
[Feature]UTF-8 Support

### ISSUE THREAD

**Issue by Threonine-Animist** [JasonStein/Notepads#119]
It seems that Notepads doesn't support UTF-8 format file yet.
It will display meaningless characters when it opens files with Chinese characters sometimes.

**Comment by JasonStein** [comment]
If the file is truly UTF-8, you should not see random characters. Otherwise it is ANSI, then you need to use ANSI mode to open the file:
![image](https://user-images.githubusercontent.com/1166162/62755581-6c01e600-ba29-11e9-8deb-52477cd31a1f.png)
I would recommend you to convert all your ANSI encoded files to UTF-8 to save your time.

**Comment by Threonine-Animist** [comment]
> If the file is truly UTF-8, you should not see random characters. Otherwise it is encoded using ANSI code page, then you need to use ANSI mode to open the file:
> ![image](https://user-images.githubusercontent.com/1166162/62755581-6c01e600-ba29-11e9-8deb-52477cd31a1f.png)
> I would recommend you to convert all your ANSI encoded files to UTF-8 to save your time.

Well I forget this setting.. I wonder if it's possible to detect its codepage automatically..

**Comment by JasonStein** [comment]
No, it is not possible in theroy (there are libraries to help detect encoding but the accuracy is a joke). Because Windows uses ANSI (Windowws Code Page) and it varies between system and region/culture. It could be some encoding that supports high ASCII or some encoding that supports Chinese characters but you never know since there is no BOM at the beigning of the file. That's why people are moving away from ANSI and use unicode encoding like UTF-8 because it supports all kinds of languages and characters. In short words, ANSI is not a specific encoding, it is the encoding that your system use based on region and culture.

**Comment by JasonStein** [comment]
References:
https://stackoverflow.com/questions/701882/what-is-ansi-format

**Comment by Threonine-Animist** [comment]
> No, it is not possible in theroy (there are libraries to help detect encoding but the accuracy is a joke). Because Windows uses ANSI (Windowws Code Page) and it varies between system and region/culture. It could be some encoding that supports high ASCII or some encoding that supports Chinese characters but you never know since there is no BOM at the beigning of the file. That's why people are moving away from ANSI and use unicode encoding like UTF-8 instead because it supports all kinds of languages and characters. In short words, ANSI is not a specific encoding, it is the encoding that your system use based on region and culture. If you want to make sure your text file will always work on any of the machines, you should use UTF-8-BOM.

OK, I learn. Thank you.
