### ISSUE TITLE
[Feature request] Display a "What's New" page when the application auto-updates

### ISSUE THREAD

**Issue by michaellewiswilson** [JasonStein/Notepads#160]
I think it would be nice to have a "What's New" tab when Notepads updates. Since it updates in the background via the Windows Store, it's not clear when it's updating and what are the new features/bugs fixed with a given release. Could be very similar behavior to VS Code as it updates.

**Comment by JasonStein** [comment]
I think about it for a while and decided to not have the "What's New" page for below reasons:

1. No one actually read "What's New" page.
2. I want to launch Notepads and start writing or editing right away without any distractions. 
3. People who are interested in "What's New" should already follow this repo and have everything they wanted and I have also added "Changelog" link in App settings.
4. I need to cooperate with translators to translate "What's New" as well. Since they do not work for me and we have our own time schedules, it is hard to sync on this and it will be guaranteed to have it translated before the release.

I hope this makes sense to you,

**Comment by JasonStein** [comment]
I won't add it, so close this for now.
