### ISSUE TITLE
[Feature request] Word counter on the statusbar please

### ISSUE THREAD

**Issue by NomadicVoxel** [JasonStein/Notepads#163]
It'd just be nice to be reminded of how long the document is. 

Just something that lists how many words are in the document. Counting the spaces. 

While we're on the topic, it might be useful to try counting sentences and paragraphs?

**Comment by JasonStein** [comment]
I have no plan to add this feature and even if I add it, it will be part of utility tools instead of showing it as built-in or by default. I am planning to add "utility" button in right click context menu and it will offer some most used features like "string <=> base64", "Json validator/formatter", "Search with ..." etc.. I will definitely consider word count as well.
