### ISSUE TITLE
[Feature request] New icon

### ISSUE THREAD

**Issue by kephax** [JasonStein/Notepads#171]
**Is your feature request related to a problem? Please describe.**
The current icon doesn't suggest a text editor but rather a console application

**Describe the solution you'd like**
A new icon in the fluent design style, similar to the new Office 2019 icons. The icon should use the green colour of the original notepad.exe . I would suggest to take inspiration from the OneNote application

**Comment by yaichenbaum** [comment]
This is just my take since I have seen several others say the same.

- The 'T' suggests text, while I can see why you might think terminal the people using terminal will know the difference.
- The fluent design icons for Microsoft Office are a brand identity and should be saved for Office.
- The icon should help indicate that the app has tabs which the current icon does already.
- The use of different shades in the current icon are perfect and give a clean look just like the app.
I am not sure why the app would need a new icon, I think it looks great how it is.

**Comment by kephax** [comment]
* 'T' suggests text, but the name of the application starts with 'N'.
* Fluent Design is the guidelines Microsoft advises for Windows 10

**Comment by yaichenbaum** [comment]
Correct, fluent design is the guidelines, but the office style with a box and initial should be reserved for office.
The icon follows the guidelines (which are very broad to begin with).
I do agree that an N might make more sense since.

**Comment by JasonStein** [comment]
Just to be honest, I could not find or I do not have a better idea for the icon at this moment, so I would prefer the current one. If you have a better idea, you can show your work and paste it here and let everyone decide. I have seen many but personally I still prefer the current one. There is no right or wrong, just pure personal taste.

**Comment by SOI7** [comment]
I think the big issue with the current icon is that it looks too much like the new Terminal app. Not that it's bad per-se, but it could cause to confusion or (worse) copyright issues. That said, I've followed the discussion and the author's desires about the icon and the app, so I tried a small mockup of what, imho, would improve it without chaging it too much:

![notepads](https://user-images.githubusercontent.com/50930970/64118789-a5afdd80-cd98-11e9-9941-db2412adb5d3.png)
![notepads_dark](https://user-images.githubusercontent.com/50930970/64118790-a6487400-cd98-11e9-8e3d-9d8d0c2cf3e4.png)

The icon has a different shape that resembles a Notepad, but it's still loyal to the original. The top tabs with different shades are still present, and the T is still there. the underscore is gone both for spacing reasons and because it's more reminiscent of a console rather than a texting app. 
Of course this is just a suggestion, but I'm open to feedback

**Comment by kephax** [comment]
I think, either we keep the current icon with an “N” instead of a “T_”, woth a green colour like the priginal notepad, or we create an icon similar to OneNote but again with a green colour and modified background. I will post some concepts

**Comment by SOI7** [comment]
But regular Notepad is blue, not green

**Comment by AmionSky** [comment]
I would say "N" would be better than "T". Especially since the app is called "Notepads" on all languages.

**Comment by kephax** [comment]
In addition, the application is called Notepads so the icon should resemble that...

**Comment by JasonStein** [comment]
I do not think the icon should or must have "N" just because the app is called Notepads. Btw, the "T" that I used in the icon is not some arbitrary character and T_ means text and it is a strong indicator. What I am trying to say here is that by changing "T" to "N" will not make it better dramatically. Until I have a better idea, I will go with what I have right now.

**Comment by AmionSky** [comment]
But "T" does not imply text in all other languages and most applications don't use underscore as caret but avertical one.

**Comment by SOI7** [comment]
> I do not think the icon should or must have "N" just because the app is called Notepads. Btw, the "T" that I used in the icon is not some arbitrary character and T_ means text and it is a strong indicator. What I am trying to say here is that by changing "T" to "N" will not make it better dramatically. Until I have a better idea, I will go with what I have right now.

What about the resizing I posted above? The T is still there, but the shape resembles a notepad more

**Comment by FJduFou** [comment]
@SOI7 
it's not good I think
simply, the format is not optimize for an icon ...

**Comment by spikespaz** [comment]
@JasonStein I would like to point out that people disagree with you on this statement:

> I do not think the icon should or must have "N" just because the app is called Notepads.

You seem to like the current icon, you're understandably biased, however your users' opinions shouldn't go unnoticed.

**Comment by yaichenbaum** [comment]
It sounds like he is open to a new icon, but he would rather spend time making the app better then work on a new icon, if anyone has an idea for an icon then they should share it.
Ultimately its a free app and up to @JasonStein  to decide.

**Comment by FJduFou** [comment]
the icon is good ^^

**Comment by JasonStein** [comment]
> @JasonStein I would like to point out that people disagree with you on this statement:
> 
> > I do not think the icon should or must have "N" just because the app is called Notepads.
> 
> You seem to like the current icon, you're understandably biased, however your users' opinions shouldn't go unnoticed.

No, I do not like the current icon that much, that is why I am keeping this thread alive and listening to all ideas. All I am saying in above threads can be summarized into below points:

1. The ideas you guys come up with are good, makes sense but are more like tweaks and modifications. I would rather spent time on code instead of tweaking the icon like changing T to N. Not saying T is better, just saying that it would not change the overall look of the icon and make it dramatically better or more appealing.

Besides, most of the people do not even know that to tweak the icon is easy. It is easy but you have to make sure it is pixel perfect. Everything you do with the icon design has to be carefully done to make sure it looks good regardless of the scale like 100%, 150%, 200% etc. 

2. These is no bias around a design, it is all about personal taste. Besides, if there are like at least 10 people asking me to change from T to N, I would definitely consider it more carefully. Even with that said, it does not mean changing from T to N will make it dramatically "better".

3. People who post questions, feature requests here are mostly people who have tech background (Most people do not even know what Github is). Notepads is not targeted purely for developers or tech people. This is a lightweight text editor for everyone. If let's say, 1000 people here ask me to change the icon to be something like a symbol which only developers know. Do you still think it is good to change? If 90% of the user base do not even know what Github is, do you still think it is a better design? One good example that I learned from above thread is that "T" only makes sense in English since it shorts for Text. If we dig more into it, we might end up translating Notepads app name into different locales.

4. I am not ignroing any feature requests or ideas here, I read every single comment. There is no requirement for me to reply to everyone, this is not stated in any of the agreements also. Instead, everyone can share your opinions and ideas here. If I do not do it or follow, it does not mean your idea is dumb or I am biased.

**Comment by spikespaz** [comment]
Sorry for misinterpreting your earlier statement?

**Comment by spikespaz** [comment]
And for the record, I like the current icon. I do not think it needs a change. Take that however you wish.

**Comment by FJduFou** [comment]
just not the pen, that's what I ask please

**Comment by yaichenbaum** [comment]
Two ideas based of the pen concept from @JasonStein 
![image](https://user-images.githubusercontent.com/39923744/64547414-8239e500-d2fa-11e9-8359-cc112564e32a.png)

**Comment by SOI7** [comment]
With a shorter underscore the second one would be the best option

**Comment by yaichenbaum** [comment]
![image](https://user-images.githubusercontent.com/39923744/64547734-3fc4d800-d2fb-11e9-9569-f528e71c86b6.png)

**Comment by kephax** [comment]
Also make it blue like the original notepad. The human brain see’s first colors then shapes.

Il giorno 9 set 2019, alle ore 18:13, Yair Aichenbaum <notifications@github.com> ha scritto:

﻿

[image]<https://user-images.githubusercontent.com/39923744/64547734-3fc4d800-d2fb-11e9-9569-f528e71c86b6.png>

**Comment by yaichenbaum** [comment]
Not a big fan of a it but here is another version
![image](https://user-images.githubusercontent.com/39923744/64548496-bc0beb00-d2fc-11e9-80f9-a50d402f089c.png)

**Comment by SOI7** [comment]
Maybe make only the tabs, the underscore and the pen colored, and leave the background white

**Comment by kephax** [comment]
What about taking the OneNote icon make it this blue color with the pen in the background? The corner pf the background should be cut like a file

Il giorno 9 set 2019, alle ore 18:24, Yair Aichenbaum <notifications@github.com> ha scritto:

﻿

Not a big fan of a it but here is another version
[image]<https://user-images.githubusercontent.com/39923744/64548496-bc0beb00-d2fc-11e9-80f9-a50d402f089c.png>

**Comment by yaichenbaum** [comment]
![image](https://user-images.githubusercontent.com/39923744/64548690-2886ea00-d2fd-11e9-81c2-9f2f2e1c6990.png)

**Comment by SOI7** [comment]
Now it looks much better. Perhaps you could make the first tab more desaturated/brighter to stand out more since it's almost the same tint of the second, but other than that I don't have other feedback. Let's wait for Jason to hear his opinion

**Comment by JasonStein** [comment]
@yaichenbaum  haha, very nice, just make the pen tip sharper like this:
![image](https://user-images.githubusercontent.com/1166162/64555116-81e91c00-d2f1-11e9-9277-cbf945fc8b3d.png)

**Comment by yaichenbaum** [comment]
Should I focus on the colored one?

**Comment by JasonStein** [comment]
forget about color for now, the pen shape need to be simple, clean and iconic. Once the pen shape is figured out, rest is easy and I can ask my designer friend to polish the final version.

**Comment by JasonStein** [comment]
@FJduFou  Feel free to share your work since you talked to me on this before and have some scratches.

**Comment by yaichenbaum** [comment]
![image](https://user-images.githubusercontent.com/39923744/64555662-cb466500-d30b-11e9-983c-9474310a17ae.png)

**Comment by JasonStein** [comment]
Maybe reduce the gap between the pen body and tip a little bit and make the tip end a slightly rounded? Overall, it looks good.

**Comment by yaichenbaum** [comment]
![image](https://user-images.githubusercontent.com/39923744/64556204-f8dfde00-d30c-11e9-93a7-7f5f6f7d7bf8.png)

**Comment by spikespaz** [comment]
![image](https://user-images.githubusercontent.com/12502988/64559084-50288300-d2fa-11e9-8f7f-19dc30e80226.png)

**Comment by Tommasov** [comment]
I agree. I'd like to use this app (It's awesome) instead of the classic notepad but the filetype icon distract me.

I would keep it simple and follow vscode icon style the txt file and office style for the app main icon.
https://dribbble.com/shots/5677309-Free-Microsoft-Office-365-icons/attachments
https://raw.githubusercontent.com/microsoft/vscode/master/resources/win32/default.ico

**Comment by Tommasov** [comment]
I agree. I like to use this app (It's awesome) instead of the classic notepad but the .txt icon distracts me, it is a little off style.
I would keep it simple and follow vscode icon style for the txt file and office style for the app main icon.
https://dribbble.com/shots/5677309-Free-Microsoft-Office-365-icons/attachments
https://raw.githubusercontent.com/microsoft/vscode/master/resources/win32/default.ico

**Comment by Tommasov** [comment]
Something like this? "E" stands for Edit... Yeah not the most appropriate
![notepadsicon](https://user-images.githubusercontent.com/9279914/64710426-3af95300-d4b8-11e9-94ae-5589f4a36f6f.png)

**Comment by kephax** [comment]
I like this the most but then with an N.
Photoshop doesn’t have a D for “draw”, but a P. Facebook doesn’t have an S for social media,...

—
Best regards

Pietro Bua

Il giorno 11 set 2019, alle ore 17:22, Tommaso Vietina <notifications@github.com> ha scritto:

﻿

Something like this? "E" stands for Edit... Yeah not the most appropriate
[notepadsicon]<https://user-images.githubusercontent.com/9279914/64710426-3af95300-d4b8-11e9-94ae-5589f4a36f6f.png>

**Comment by Tommasov** [comment]
Yep, I've got u but "N" is used by OneNote :( Source for improvement:
[notepadsicon.pdf](https://github.com/JasonStein/Notepads/files/3601534/notepadsicon.pdf)

**Comment by carlinmack** [comment]
The new icon isn't going to follow the design of the microsoft suite so it doesn't matter that the letters clash. I think a vertical icon with an N or pen would work best. I think vertical is important as paper is mainly written on in portrait orientation.

Writing on this issue as the current icon is _very_ similar to the windows terminal icon and I keep opening the wrong app
![image](https://user-images.githubusercontent.com/6676843/68308520-fbe01c00-007a-11ea-935a-3b3085fcae0d.png)

**Comment by Tommasov** [comment]
> The new icon isn't going to follow the design of the microsoft suite so it doesn't matter that the letters clash. I think a vertical icon with an N or pen would work best. I think vertical is important as paper is mainly written on in portrait orientation.
> Writing on this issue as the current icon is very similar to the windows terminal icon and I keep opening the wrong app

Yep, I agree.
.txt filetype icons should be upgraded as well. The actual one doesn't fit the Windows 10 UI

**Comment by mah-qurashy** [comment]
Windows Notepad has a new icon in the windows store, maybe we could make a one that is inspired from this
![Untitled](https://user-images.githubusercontent.com/20822445/77479148-e865ff80-6e27-11ea-8742-d7d6b3ecb268.png)

**Comment by mah-qurashy** [comment]
any thoughts about this? ![newnotepads](https://user-images.githubusercontent.com/20822445/77492961-8965b200-6e4a-11ea-80fb-0a04b62b5253.png)

**Comment by JasonStein** [comment]
Not bad at all, can give it more shadow behind pen. And I think the font of character "N" can be better. What about a white one for dark mode?

**Comment by yaichenbaum** [comment]
It looks really good but I think it looks too similar to the built-in Notepad apps icon.

**Comment by mah-qurashy** [comment]
> Not bad at all, can give it more shadow behind pen. And I think the font of character "N" can be better. 

how about this for a change?
![newnotepads](https://user-images.githubusercontent.com/20822445/77542077-4f2dfc00-6eae-11ea-9677-dfcf0a8d937a.png)

> What about a white one for dark mode?

did some experimenting with a lighter version, did not like the way it came out, maybe we could just ditch the concept of having dark and light version of the icon? maybe change this to colored instead of black?
also i like the idea of the main app icon being dark, Notepads is widely mentioned as notepad with dark mode support.

> It looks really good but I think it looks too similar to the built-in Notepad apps icon.

there's definitely a room for improvement, do you have any ideas for a change?

**Comment by kephax** [comment]
> any thoughts about this? ![newnotepads](https://user-images.githubusercontent.com/20822445/77492961-8965b200-6e4a-11ea-80fb-0a04b62b5253.png)

I like this but i would still use some green colour instead

**Comment by SOI7** [comment]
Personally I'd remove the lowest later (the black one at the bottom) and detach the pen from the lines below it (or perhaps have only a single line, drawn by the pen) The font for the N looks better in the last concept

**Comment by JasonStein** [comment]
I actually like the idea of the icons you shared above but it needs to be more polished. Feel free to sent out more variants for all of us to review. Thanks!

**Comment by mah-qurashy** [comment]
something a bit different
![newnotepads](https://user-images.githubusercontent.com/20822445/79930122-f2d7e100-8447-11ea-9864-ef5d8a22b269.png)

**Comment by JasonStein** [comment]
@mah-qurashy  I like it very much but I think the icon should also be modern/stylish/acrylic like so it can fit the overall looking of the app. Which means:
1. The material look of the cover texture should be adjusted: maybe remove the dashed outline?
2. "N" is a little bit cartoonish to me.

The overall design and color choices are great!

**Comment by mah-qurashy** [comment]
> @mah-qurashy I like it very much but I think the icon should also be modern/stylish/acrylic like so it can fit the overall looking of the app. Which means:
> 
> 1. The material look of the cover texture should be adjusted: maybe remove the dashed outline?
> 2. "N" is a little bit cartoonish to me.
> 
> The overall design and color choices are great!

there you go
straightened the letter N, removed the dashed outline and added a tiny bit of noise to the background
![newnotepads](https://user-images.githubusercontent.com/20822445/79938248-61bf3500-845c-11ea-9fcf-eac8d190c662.png)

**Comment by JasonStein** [comment]
@mah-qurashy  Can you paste some more screenshots to see what it looks like on task bar, tiles etc?

**Comment by mah-qurashy** [comment]
> @mah-qurashy Can you paste some more screenshots to see what it looks like on task bar, tiles etc?

for the final version i would do some sharpeneing and pixel perfect modifications on smaller sizes
i didn't do this yet for these screenshots, this is just resizing

![Untitled-3](https://user-images.githubusercontent.com/20822445/79940389-dba5ed00-8461-11ea-9332-05aa22e2a5a4.png)
![Untitled-2](https://user-images.githubusercontent.com/20822445/79940396-dd6fb080-8461-11ea-8ae8-e4c874c1f854.png)

**Comment by mah-qurashy** [comment]
@JasonStein also been considering a version that has a pencil 
![newnotepads](https://user-images.githubusercontent.com/20822445/79940872-368c1400-8463-11ea-8764-22344d1dad1c.png)

**Comment by JasonStein** [comment]
> @JasonStein also been considering a version that has a pencil
> ![newnotepads](https://user-images.githubusercontent.com/20822445/79940872-368c1400-8463-11ea-8764-22344d1dad1c.png)

The color looks good when in large scale but it still looks very cartoonish in small sizes. Maybe a darker one or change to something else to make it feel more "professional"?

**Comment by mah-qurashy** [comment]
> The color looks good when in large scale but it still looks very cartoonish in small sizes. Maybe a darker one or change to something else to make it feel more "professional"?

![Untitled-2](https://user-images.githubusercontent.com/20822445/79949761-57aa3000-8476-11ea-9d36-1dbec366c29d.png)

here's how the one with the pencil would look, did some desaturation, also made the whites much less brighter which i think make it less cartoonish to some extent
i think it still can be improved though

**Comment by SOI7** [comment]
The cartoonish look probably will never go away, because it's Microsoft's new design language that is cartoonish on purpose. I was actually wondering how it would look if the N, the underscore and the pen had softer/blurred shadows rather than the sharp ones they have now. Also, splitting the N into three overlapped lines with shadows rather than the two pieces you have now could be interesting

**Comment by FJduFou** [comment]
without pencil and the "N" in one part is very good as for me, can you try @mah-qurashy ?

**Comment by mah-qurashy** [comment]
@SOI7 
![newnotepads2](https://user-images.githubusercontent.com/20822445/80049408-1a47b000-8513-11ea-8dc7-d4bee932c17f.png)
@FJduFou 
![newnotepads3png](https://user-images.githubusercontent.com/20822445/80049417-203d9100-8513-11ea-9696-9f650576f9f9.png)
i also discovered that the screenshots i made had notepads icon 4 pixels larger than every other app icon, so here's how it would rather look in terms of size
![Untitled-2](https://user-images.githubusercontent.com/20822445/80049546-78749300-8513-11ea-8678-9ddfaf1dde5b.png)

**Comment by SOI7** [comment]
Soft shadows really help

**Comment by FJduFou** [comment]
![image](https://user-images.githubusercontent.com/46401854/80092865-ce712700-8563-11ea-967a-e4028b0b1bff.png)
as for, this is a problem, this make 2 little white points

**Comment by mah-qurashy** [comment]
> as for, this is a problem, this make 2 little white points

this is true, as i said this is just resizing
smaller sizes could be redrawn to have more readability
![Untitled-3](https://user-images.githubusercontent.com/20822445/80100039-ae476500-856f-11ea-8094-7d3138337b31.png)

**Comment by JasonStein** [comment]
@mah-qurashy I think we should just remove the pencil, reason is simple: It looks good on large icon but since user will spend more time on viewing the smaller ones, we should just make sure the smaller icon looks solid and good. Thoughts?

**Comment by JasonStein** [comment]
![image](https://user-images.githubusercontent.com/1166162/80184216-06598800-85bf-11ea-8d9a-b4b8594a6676.png)
Can you remove the pencil in this one and show the small variants here? @mah-qurashy

**Comment by mah-qurashy** [comment]
@JasonStein 
![newnotepads](https://user-images.githubusercontent.com/20822445/80191933-b8706e80-8616-11ea-9d58-23972feccc8a.png)
![Untitled-2](https://user-images.githubusercontent.com/20822445/80191970-c7572100-8616-11ea-9199-1599ea647fab.png)
![Untitled-3](https://user-images.githubusercontent.com/20822445/80191941-b9a19b80-8616-11ea-8154-1fdc3868e4f8.png)

**Comment by mah-qurashy** [comment]
also we could use the current icon color theme
![Untitled-2](https://user-images.githubusercontent.com/20822445/80205000-2f633280-862a-11ea-952b-a37758011086.png)

**Comment by mah-qurashy** [comment]
![Untitled-1](https://user-images.githubusercontent.com/20822445/80206680-13ad5b80-862d-11ea-9188-1a39b1e484d1.png)

**Comment by FJduFou** [comment]
yes, very good

**Comment by soumyamahunt** [comment]
> ![Untitled-1](https://user-images.githubusercontent.com/20822445/80206680-13ad5b80-862d-11ea-9188-1a39b1e484d1.png)
> 

The bottom bar for dark icon should be reverse of the light icon. Also can you make the width bit more to make it rectangular rather than square.

**Comment by FJduFou** [comment]
> The bottom bar for dark icon should be reverse of the light icon. Also can you make the width bit more to make it rectangular rather than square.

Yea, why not, for reverse.
But for the square, I'm not agree with you because if more square, the bot is more big and don't follow this:
![image](https://user-images.githubusercontent.com/46401854/80253423-89d7af80-8679-11ea-9a84-95f879c57b68.png)
(New terminal icon)

**Comment by mah-qurashy** [comment]
did reverse bottom bar and slightly increase vertical length
![Untitled-1](https://user-images.githubusercontent.com/20822445/80267857-9b35b180-86a3-11ea-8ba1-3b81e922a718.png)

**Comment by JasonStein** [comment]
@mah-qurashy 
![image](https://user-images.githubusercontent.com/1166162/80268034-39e8f080-8659-11ea-9139-eb1bb52b8ff0.png)
Can you increase the overall shadow behind all elements and especially the bottom edge? I feel it will look better in small sizes. And can you paste them in small sizes as well? looks like we are on the good track for a new icon. Thanks for the hard work! Really appreciate!

**Comment by mah-qurashy** [comment]
@JasonStein 
![Untitled-1](https://user-images.githubusercontent.com/20822445/80298799-28563480-8790-11ea-80c5-d1a805331f99.png)
![Untitled-3](https://user-images.githubusercontent.com/20822445/80298800-29876180-8790-11ea-8dae-9ed0d60c5db3.png)

**Comment by mah-qurashy** [comment]
![Untitled-2](https://user-images.githubusercontent.com/20822445/80299050-a404b100-8791-11ea-90e6-da40ad2b3087.png)

**Comment by JasonStein** [comment]
Looks pretty good, what about shadow under "N" and "_"?

**Comment by mah-qurashy** [comment]
> Looks pretty good, what about shadow under "N" and "_"?

i actually removed that because it would be barely visible on the dark icon, also on the light one it would make the N_ look a bit blurry for smaller sizes
![image](https://user-images.githubusercontent.com/20822445/80567571-bed75f80-89f5-11ea-9db4-22579cd047c7.png)

**Comment by JasonStein** [comment]
> > Looks pretty good, what about shadow under "N" and "_"?
> 
> i actually removed that because it would be barely visible on the dark icon, also on the light one it would make the N_ look a bit blurry for smaller sizes
> ![image](https://user-images.githubusercontent.com/20822445/80567571-bed75f80-89f5-11ea-9db4-22579cd047c7.png)

You are right, the shadow has to be darken enough to make it stands out, otherwise we should drop the shadow at all. Take windows terminal's icon as example:

<img width="418" alt="Screen Shot 2020-04-29 at 6 18 47 AM" src="https://user-images.githubusercontent.com/1166162/80600475-4e264800-89e1-11ea-867d-6919692f6b5b.png">

Btw, make sure your icon is pixel perfect so it won't look blurry when downscale to relative sizes.
In case you don't know, this is what I mean: https://icons8.com/articles/make-pixel-perfect-icons/

**Comment by JasonStein** [comment]
Thanks @mah-qurashy for the hard work! Now we have a new redesigned icon!
![Screen Shot 2020-05-01 at 6 12 42 PM](https://user-images.githubusercontent.com/1166162/80851581-6c559900-8bd7-11ea-9d95-a63c0a915169.png)

**Comment by JasonStein** [comment]
Closing this thread for now unless someone has a better idea. I am pretty satisfied with @mah-qurashy 's work here. I think this is exactly what I wanted 🤟

**Comment by mah-qurashy** [comment]
in case someone is interested, i have uploaded psd files for the new icons at https://github.com/mah-qurashy/Notepads-Icon

**Comment by stamminator** [comment]
You guys nailed it on the icon, btw. Looks fresh. I had a giddy little jump for joy when I saw the new icon appear on my start menu after an auto-update.

**Comment by sotakal** [comment]
Yeah, I too just want to say great job on the icon - fits well into the new Windows icon family while still resembling what it was previously. Well done.
