### ISSUE TITLE
[Bug] Double-click + drag and triple-click in the markdown preview doesn't work

### ISSUE THREAD

**Issue by AndreasFurster** [JasonStein/Notepads#204]
Normally when you select text with double-click and drag, you keep selecting words. This does work as expected in the editor but not in the markdown preview. 
A triple click should select the whole line. This is again working in the editor but not in the Markdown preview. 

**Desktop:**
 - OS: Windows 10 - Version 10.0.18362 Build 18362
 - Version [e.g. v0.10.2.0 Beta]

**Comment by JasonStein** [comment]
This is a default behavior comes from [MarkDownTextBlock] https://docs.microsoft.com/en-us/windows/communitytoolkit/controls/markdowntextblock 
The reason is due to the way how each line or markdown token is been rendered and constructed. It is not easy to make it work as same as a normal text box. On the other hand, if you want to select a block of text, you can always go to the plain text area. So I do not think this is a blocker.

**Comment by AndreasFurster** [comment]
Hmmm. It seems to be related to this issue:
https://github.com/windows-toolkit/WindowsCommunityToolkit/issues/1746

I use the preview pane to read notes. Proper select in there would be very useful.

**Comment by JasonStein** [comment]
> Hmmm. It seems to be related to this issue:
> [windows-toolkit/WindowsCommunityToolkit#1746](https://github.com/windows-toolkit/WindowsCommunityToolkit/issues/1746)
> 
> I use the preview pane to read notes. Proper select in there would be very useful.

Yeah, that confirms my guess. I feel like it is a dramatic change to the underline implementation so I will probably not do it myself and let them fix it if possible.
