### ISSUE TITLE
[Bug] cannot open files from cmd or powershell or any terminal app

### ISSUE THREAD

**Issue by trip23app** [JasonStein/Notepads#220]
**Describe the bug**
opening any file doesn't work from a terminal or cmd or powershell.

**To Reproduce**
Steps to reproduce the behavior.

1. Open cmd or powershell. If the file is present and called rat.txt
2. paste `notepads rat.txt` in terminal.
3. notepads opens, but the file is not opened in it.
4. also, now the terminal is unusable. the cursor keeps blinking but nothing appears when you type text. Even, <kbd>Ctrl+C</kbd> doesn't work. closing the notepads window works.

**Expected behavior**
type `notepad rat.txt` , notepad opens the file. and you can continue to type other commands in the same terminal.

vscode also does something like notepad, I think. other text editors also do this basic task.

**Screenshots**
None.

**Desktop (please complete the following information):**
 - OS: Windows 10 1903
 - Version 0.10.3.0

**Additional context**

`notepads help` or `notepads -h` doesn't work. 
similar issue for printing the version of notepads.
 
actually, even typing `notepads` in the terminal, presents the same issues. the file is not opened, terminal is unusable.

my user account is not admin, so can't change some settings. there is a admin account. and "transparency effects" are turned off.

**Comment by trip23app** [comment]
tags:?

**Comment by trip23app** [comment]
connected issues: ?

**Comment by JasonStein** [comment]
For opening files within CMD and PowerShell, it should work. Can you do a quick screen recording of your scenario?

Notepads "help" or "-h" is not implemented since this is not a command-line app and I do feel a need of doing so (Same as original notepad.exe).

For answering why running Notepads command in PowerShell will "hang" or becoming "unusable" is because PowerShell runs Notepads command in the main thread and by default, it is waiting for the command to finish, in this case: it will finish after closing the app. If you run below command in PowerShell, it will run the command in a background thread:
```
> Start-Process -NoNewWindow Notepads
```
This is a behavior change brought by implementing UWP multi-instance feature. Not sure why and I can take a look later.

**Comment by trip23app** [comment]
it works, i tried it with different files and it works flawlessly. sorry to bother you.

thanks for the app and for `> Start-Process -NoNewWindow Notepads` suggestion.
