### ISSUE TITLE
[Feature request]Portable installation

### ISSUE THREAD

**Issue by linsui** [JasonStein/Notepads#276]
**Is your feature request related to a problem? Please describe.**
Notepads must be installed. 

**Describe the solution you'd like**
Would it be possible to make it portable so that I can extract files from msix, just like Windows Terminal? Thanks!

**Comment by JasonStein** [comment]
There is already a package installer available, can you describe your need more specifically or share me with some pointers?

**Comment by linsui** [comment]
Thanks for your reply. I would like to install notepads as a potable app so that I can use it in a USB. Windows Terminal can work without installation but I don't know how it does that, see https://github.com/microsoft/terminal/issues/1386 .

**Comment by JasonStein** [comment]
I will consider if there is an existing solution that I can borrow very quickly. I do not have time to look into this ask yet.

**Comment by JasonStein** [comment]
I took a look and don't find a good way to do it, so closing the thread for now.

**Comment by survivor303** [comment]
im not sure if this is for request of classic installer, installer that works outside of store or msix.

but im fan of that idea too, i dont like to use store at all (but love notepads), i use chocolatey for windows package manager, but because of msix "installer" i cannot add notepads to chocolatey :(
