### ISSUE TITLE
[Feature request] Use 13, 15, 17 (odd) number font-sizes

### ISSUE THREAD

**Issue by stanio** [JasonStein/Notepads#292]
**Is your feature request related to a problem? Please describe.**
Cannot select font-size of 13, 15, 17, etc. odd numbers.

**Describe the solution you'd like**
I would like an option to select 13, 15 or 17 font-size numbers.  Larger font-sizes might not need such fine-grained selection, but maybe the drop-down could be made editable for manual input.

**Comment by JasonStein** [comment]
https://ux.stackexchange.com/questions/129973/why-rounding-odd-font-sizes-to-even

**Comment by stanio** [comment]
As far as I've got from the reference it is not an issue with high-dpi displays, and for standard resolution displays, it is likely subjective perception – so why not let the user decide?  I guess, if the drop-down field is made editable the selection list could still contain only current options but allow for entering the odd values.

**Comment by JasonStein** [comment]
Yes you are right, it should look normal for high DPI displays. And yes "Larger font-sizes might not need such fine-grained selection". That's why I think "8, 9, 10, 11, 12, 14, 16, 18, 20, 22, 24, 26, 28, 36, 48, 72" are good selections. Most of the users pick either 12 or 14 so I am agree I should add 13 as well but maybe not 15 or 17.

**Comment by JasonStein** [comment]
https://github.com/JasonStein/Notepads/commit/82f0f926e0c5d638f8ada353115ca3a90f590894

**Comment by stanio** [comment]
Thank you very much!

**Comment by JasonStein** [comment]
It will be viable in Notepads v1.1.0.0, which will be release very soon.
