### ISSUE TITLE
[Question] Why connection to IP "52.232.222.105"

### ISSUE THREAD

**Issue by beerisgood** [JasonStein/Notepads#334]
Notepads try to connect to IP 52.232.222.105:443 TCP (unsigned)
which is from Microsoft Corporation.

Just asking why this connection is opened.
<img width="255" alt="notepads" src="https://user-images.githubusercontent.com/9625159/76148034-4c539e80-609a-11ea-97a7-01452aa43fea.png">

**Comment by JasonStein** [comment]
There are three kinds of scenarios Notepads might reach to the network:

1. All Windows store app will have some basic diagnostic info sent to MSFT and I have no control over that. You can disable it in the global Windows settings.

2. In the Markdown preview panel, if there is any network image in your markdown file, it will try download from the url.

3. AppCenter (which should be the case that you are seeing since it is going to a MSFT IP). I am using Visual Studio AppCenter to track App crashes and basic usage info reported by user. This service should be GDPR Compliance (meaning there is no way to trace back to a certain user and your identity including your IP address will be hidden while using the service). 

If you search "Analytics.TrackEvent" and "Crashes.TrackError" in this repo, you will see what event or crash point I am tracking using AppCenter. Bottom line is, I am not tracking any user privacy related info and I am not sending any of your typing or files over to me, AppCenter or any third party services.

I care so much that I am not even tracking for any file opening crashes or saving crashes since your content might be exposed in the crash event. Also, I am not even tracking things like your custom search query for the default Search Engine setting since it might expose your identity as well.

Please feel free to check Notepads code base to see if there is any tracking event that you think might violate user privacy and I will fix ASAP. Also, feel free to build your own version of Notepads since code is 100% open sourced.

**Comment by beerisgood** [comment]
Very good answer!
Will allow the IP.

Maybe you should add that info somewhere for new user's which fear telemetry or something
I close this as solved.

**Comment by JasonStein** [comment]
> Very good answer!
> Will allow the IP.
> 
> Maybe you should add that info somewhere for new user's which fear telemetry or something
> I close this as solved.

I am going to attach this thread to README.

**Comment by obeho** [comment]
@JasonStein I'm using [Simplewall](https://github.com/henrypp/simplewall) app, which auto-blocks any new connections being made to or from the machine (except those specifically allowed). Can I run the Notepads app in an offline mode?

I finally successfully installed it, but when I try to add the Notepads app to the list of allowed apps, I can't seem to find where the app got installed. And upon app launch, it just closes automatically, don't know why.

**Comment by soumyamahunt** [comment]
> @JasonStein I'm using [Simplewall](https://github.com/henrypp/simplewall) app, which auto-blocks any new connections being made to or from the machine (except those specifically allowed). Can I run the Notepads app in an offline mode?
> 
> I finally successfully installed it, but when I try to add the Notepads app to the list of allowed apps, I can't seem to find where the app got installed. And upon app launch, it just closes automatically, don't know why.

Notepads should run fine in offline, just the crash-analytics won't be sent. I think your issue is related to something else, probably using any debloating tool that removed some dependency for Notepads. Can you check event viewer what error you are facing?? Notepads should be installed in the following directory:
`C:\Program Files\WindowsApps\19282JackieLiu.Notepads-Beta_1.4.2.0_x64__echhpq9pdbte8`

**Comment by obeho** [comment]
Hello, I checked under Event Viewer(Local) -> Windows Logs -> System, and I don't see any new logs.

**Comment by usernamebutexists** [comment]
> Notepads try to connect to IP 52.232.222.105:443 TCP (unsigned) which is from Microsoft Corporation.
> 
> Just asking why this connection is opened. <img alt="notepads" width="255" src="https://user-images.githubusercontent.com/9625159/76148034-4c539e80-609a-11ea-97a7-01452aa43fea.png">

can i know what is this software name in the image which you've used to notify about outgoing connection from you pc

**Comment by emidiofbrasil** [comment]
Hello. I wish you are well!

I searched but couldn't find to display the markdown view.

**Comment by sekedus** [comment]
> can i know what is this software name in the image which you've used to notify about outgoing connection from you pc

[Windows Firewall Control by BiniSoft](https://www.binisoft.org/wfc)
