### ISSUE TITLE
Presentation of the umlauts

### ISSUE THREAD

**Issue by Zig12** [JasonStein/Notepads#35]
Hello Jason,

I liked the text editor. Thanks for that. Would like to use it permanently, but he does not accept the umlauts (ä, ö, ü, ß) for existing (old) text documents. Text documents created with notepads (New) are displayed correctly when reopened.

![Test](https://user-images.githubusercontent.com/35289434/60802893-40fe4b00-a17a-11e9-8b4c-459bb386cb3d.jpg)

Would be nice if you could find a solution there.

Greetings Zig

**Comment by JasonStein** [comment]
Can you send me your old files? NotepadsApp@outlook.com

**Comment by JasonStein** [comment]
I need to add ANSI supports in my App since your file has Extended ASCII char. In your case, it can be opened with windows-1252 codepage correctly. I am not expert on encoding, if someone interested or familiar with encoding, feel free to leave your comments. Thanks in advance!

References:
https://en.wikipedia.org/wiki/Extended_ASCII
https://stackoverflow.com/questions/2014069/windows-1252-to-utf-8-encoding

**Comment by JasonStein** [comment]
Most of the legacy editors like older version of notepad uses ANSI as default encoding and does not emit BOM, so it becomes harder and harder for newer editors to recognize the correct encoding to use.

There are two ways to solve this problem:

1. Write some hacky code to determine high-ASCII chars and use custom encoding like windows-1252 to load the file.
2. [You need to] Open this file in notepad.exe and save it with UTF-8 encoding, so it can be opened correctly with Notepads in the future:
![image](https://user-images.githubusercontent.com/1166162/61007191-0d115a00-a321-11e9-8de4-6f8be7717efc.png)

I prefer option 2 since I need to handle the cases not only for certain characters but other non-English languages as well, like Chinese (which uses GBK).

**Comment by SilentException** [comment]
Hi, I would like to chime in on this one because I also noticed this problem with my Windows-1250 ANSI files (quite a lot of them here). Usually, editors have user option for default encoding for non-UTF8 files (fallback encoding). I have also seen Open With Encoding action in menus in some as extra.

**Comment by JasonStein** [comment]
Yes, I agree:
https://stackoverflow.com/questions/90838/how-can-i-detect-the-encoding-codepage-of-a-text-file
https://www.joelonsoftware.com/2003/10/08/the-absolute-minimum-every-software-developer-absolutely-positively-must-know-about-unicode-and-character-sets-no-excuses/

@SilentException , what is your system language and what is your defualt code page?

**Comment by SilentException** [comment]
I have system language set to English, however regional settings to Croatian and usually I work with UTF-8 text files but if the files are ANSI, my encoding is set to Windows-1250. I'm not sure from where Windows notepad.exe gets it's ANSI charset info (doesn't have any setting for it) but it is probably from system regional settings.

For example, relevant line from Sublime Text Preferences.sublime-settings file:
	"fallback_encoding": "Central European (Windows 1250)"

Hope it helps.

**Comment by JasonStein** [comment]
I am still looking into this and trying to find a cleanest solution, I will use this thread to keep all information that I found online as reference and I will start the work once I feel I am ready. If there is no direct or magic way that I can do to use active code page, I will provide settings to let user change default encoding when Notepads reads the file.

https://docs.microsoft.com/en-us/windows/uwp/design/globalizing/use-utf8-code-page

**Comment by JasonStein** [comment]
This should work: 
            var culture = Thread.CurrentThread.CurrentCulture;
            var codepage = culture.TextInfo.ANSICodePage;
And if user use ANSI as default instead of UT8, Notepads will use whatever code page this method returns as Encoder code page.

**Comment by JasonStein** [comment]
![image](https://user-images.githubusercontent.com/1166162/61691193-db649f80-acdf-11e9-8d35-13401bf92840.png)
@Zig12

**Comment by JasonStein** [comment]
https://github.com/JasonStein/Notepads/commit/3bc2f8c834a5bd406a1873ec30bcd113c2409cda

**Comment by JasonStein** [comment]
Close this issue since v0.9.6.0 is alive.

**Comment by Zig12** [comment]
Hello Jason,

Thank you for your work. Works well now.
Thanks also to all the other participants who contributed to the solution.

Best regards
Zig12
