### ISSUE TITLE
[Feature request] Multi-instance

### ISSUE THREAD

**Issue by joseppinilla** [JasonStein/Notepads#41]
Tabs are great, but I think multiple windows/instances should still be a possibility.

This would work with a "New Window" button in the main menu, ctrl+N (ctrl+T for tab), as well as shift-click on the taskbar icon; that's default behaviour.

I'm looking at the **Multi-Instance App Project Templates.VSIX**
https://docs.microsoft.com/en-us/windows/uwp/launch-resume/multi-instance-uwp

**Comment by joseppinilla** [comment]
I won't makes this a PR yet, but this is a start.

joseppinilla/Notepads@4f7c8d97a227d0778ecc3ec716a342f363c04b8b

The behaviour with just that, is to open a new instance on shift-click, but also every time a new file is opened.

I'm also new to UWP, so I'm slowly looking at how to make things work the right way.

**Comment by JasonStein** [comment]
Sounds good to me, I have not started work on session saving and multi-instance thingy because the code base is not well written to support such scenarios easily. I am currently working on rewritting/refactoring existing code. I will get back to this later. Feel free to dig more into it and share your knowledge here. Thanks!

**Comment by JasonStein** [comment]
![image](https://user-images.githubusercontent.com/1166162/63247523-16dc8600-c21a-11e9-8b4d-5bfea69b1e92.png)

Almost finished.

**Comment by JasonStein** [comment]
This feature has been implemented in v0.9.9.0.
