### ISSUE TITLE
[Bug] Replace starts from the end of the currently selected text

### ISSUE THREAD

**Issue by AmionSky** [JasonStein/Notepads#49]
When you use 'Find' it selects the text that matches.
When you use 'Replace' it seems to start from the end of the currently selected text.

But it does not allow to use search to quicly find the exact place you were looking for and then just press replace, since it will try to find the next match to replace.

Notepad replaces the currently selected text.

**Comment by AmionSky** [comment]
Also 'Find' cycles back to the beginning, 'Replace' does not. (Unsure if its intended)

**Comment by AmionSky** [comment]
When pressing replace in Notepad, it always just selects the first match. Pressing replace again replaces it and moves the selection to the next match. Both VS and vscode seems to work the same way.

**Comment by JasonStein** [comment]
Replace stops because it should gives user more control of what will be replaced. The idea of starting from selected index is also the same: It gives user fine control on what should be replaced. For example, you may only want to replace certain text in the last 20 lines of the file. In this case, it should not starts from first line and it should not do cycles as well. "Replace All" is a different story, so it starts from zero and actually replace all occurrence.

**Comment by JasonStein** [comment]
Closing this thread since this is an indented behavior.
