### ISSUE TITLE
[Feature request] Possibility to select language instead of using Windows preferred one.

### ISSUE THREAD

**Issue by Diego251** [JasonStein/Notepads#498]
**Is your feature request related to a problem? Please describe.**
I have a fr-ch keyboard so I need to set French as a preferred language in Windows. But then the interface of Notepads is also in French, while I would prefer it in English.

**Describe the solution you'd like**
Ability to set the interface language in Notepads' settings.

**Describe alternatives you've considered**
Use the application in French.

**Additional context**
n/a

**Comment by JasonStein** [comment]
I don't have a plan for adding this kind of support. I don't think it is needed for 95%+ of the userbase. And since you are using French, you should have no problem reading it right? I want to keep the settings as minimum as possible instead of throwing everything into it. Once the number of options in the settings reaching to a certain number, new user coming to notepads will just ignore it completely. The amount of information will become overwhelming to average user.

**Comment by Diego251** [comment]
Ok, no problem. Anyway thanks a lot for providing this tool :)
