### ISSUE TITLE
Select all includes line break

### ISSUE THREAD

**Issue by guzzd** [JasonStein/Notepads#559]
**Describe the bug**
Line break is included when selecting all (ctrl + a). Windows notepad doesn't do this.

**To Reproduce**
Just write something in one line, select all and paste somewhere else. Line break is added.

**Expected behavior**
No breaks included.

**Desktop (please complete the following information):**
 - Windows 10 1909

**Comment by JasonStein** [comment]
In the next release, there will be a feature called "Smart Copy" which should solve your problem here.

![image](https://user-images.githubusercontent.com/1166162/83296978-92566500-a1a6-11ea-893e-811b208fbf43.png)

Before:
![image](https://user-images.githubusercontent.com/1166162/83297024-a5693500-a1a6-11ea-81b3-627822afb73d.png)
After Ctrl+C or Copy:
![image](https://user-images.githubusercontent.com/1166162/83297036-adc17000-a1a6-11ea-8e60-e284f4233acd.png)

**Comment by guzzd** [comment]
That's great, thanks!
