### ISSUE TITLE
[Feature request] Add a drop shadow to the Start Menu tile to match the official Fluent icons

### ISSUE THREAD

**Issue by Spyromaniac31** [JasonStein/Notepads#567]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
The Start Menu tile for Notepads would have a drop shadow underneath the icon similar to the official Fluent icons, as shown in the screenshot.
![image](https://user-images.githubusercontent.com/55723056/83280423-dbe98480-a193-11ea-9ba4-51f55788ab85.png)

**Comment by JasonStein** [comment]
@mah-qurashy

**Comment by mah-qurashy** [comment]
yes, this makes sense. i will do some testing and see how it looks, might have to scale down the icon a bit so it doesn't look too big with added shadow

**Comment by Spyromaniac31** [comment]
If you don’t mind sending me the icon I could see what I can do. I have experience making Fluent icon tiles and think I have the drop shadow specs down pretty close to the official.

**Comment by mah-qurashy** [comment]
@Spyromaniac31 you can find all icons in the [assets folder](https://github.com/JasonStein/Notepads/tree/master/src/Notepads/Assets) in the repo, for start menu tiles you will need to add shadow to the following files:

medium tile:
```
Square150x150Logo.scale-100.png
Square150x150Logo.scale-125.png
Square150x150Logo.scale-150.png
Square150x150Logo.scale-200.png
Square150x150Logo.scale-400.png
```
wide tile:
```
Wide310x150Logo.scale-100.png
Wide310x150Logo.scale-125.png
Wide310x150Logo.scale-150.png
Wide310x150Logo.scale-200.png
Wide310x150Logo.scale-400.png
```
large tile:
```
LargeTile.scale-100.png
LargeTile.scale-125.png
LargeTile.scale-150.png
LargeTile.scale-200.png
LargeTile.scale-400.png
```
small tile: 
```
SmallTile.scale-100.png
SmallTile.scale-125.png
SmallTile.scale-150.png
SmallTile.scale-200.png
SmallTile.scale-400.png
```

**Comment by Spyromaniac31** [comment]
Here they are. I used `appicon_w.png` for the tiles, but I noticed that the existing tiles used a different, more gray icon. However, the tiles still look good, if I do say so myself.
[Assets.zip](https://github.com/JasonStein/Notepads/files/4719133/Assets.zip)

**Comment by mah-qurashy** [comment]
@Spyromaniac31 yes i think the shadow looks good, however you should not add shadow to `appicon_w.png` and make smaller sizes out of it, smaller icons are made individually to be pixel perfect, resizing the larger icon does not look as sharp
here is a comparison, look closely at the edges, edges of the original image are aligned to pixel grid
![image](https://user-images.githubusercontent.com/20822445/83588667-2aab6b80-a552-11ea-9731-6446d25f182f.png)
i think you should add shadow individually to each image and avoid resizing

**Comment by Spyromaniac31** [comment]
Thanks for the feedback. These ones should be pixel perfect. 
[Assets.zip](https://github.com/JasonStein/Notepads/files/4724803/Assets.zip)

**Comment by JasonStein** [comment]
This is how it looks like ^
![image](https://user-images.githubusercontent.com/1166162/83687051-12fad400-a5a0-11ea-85ac-bddb68aa7c4d.png)
![image](https://user-images.githubusercontent.com/1166162/83687128-2efe7580-a5a0-11ea-8db2-4a11f1e6b10f.png)
I think it looks good.

**Comment by mah-qurashy** [comment]
@Spyromaniac31 @JasonStein okay now this is good, i see you went for increasing image dimensions to make the icon smaller in the tile, for example `Square150x150Logo.scale-100.png` is now 164x164
I'm not sure if it is worth sticking with these sizes, they are recommended sizes but they are questionable as discussed in #499 
here is how it looks with native scaling compared to older icon
![image](https://user-images.githubusercontent.com/20822445/83686310-46fae700-a5ea-11ea-9a1d-e4f3059e7b62.png)
to stick with the recommended size of 150x150, we could play the mix and match game of icon sizes to make icons smaller and avoid resizing at the same time, for example, we already have a 44x44 icon in the `GameBar` folder, if this icon with used in the 150x150 canvas, here's how it looks (i tried to recreate shadow effect)
![image](https://user-images.githubusercontent.com/20822445/83687968-e7eaa180-a5ec-11ea-8507-135d5d37ee46.png)
i think windows does a better job if you use to the 150x150 size, the difference is not massive though
if we decide to stick to standard sizes, we might have to recreate newpixel perfect icons from psd, they should be a few since we already have lots of sizes that can be used

**Comment by Spyromaniac31** [comment]
Not sure why the sizes of the png changed. Figma, which I used to add the shadow, shows the tile as 150x150, but it exports to 164x164. I can look into that later.

**Comment by JasonStein** [comment]
@Spyromaniac31 Are you still working on it or do you need help from @mah-qurashy?

**Comment by Spyromaniac31** [comment]
@JasonStein Sorry, I wasn't exactly sure what the final verdict was on the sizes. I can try to make tiles in the original sizes tomorrow so you can compare them.

**Comment by bnayagrawal** [comment]
If someone can colorize this icon with Windows XP's default Luna Blue color scheme, then it would look great IMO. I would have done that (If people like it), but currently, I don't have my desktop with me and my laptop is having scaling issues with adobe apps, so I cannot do that.

**Comment by mah-qurashy** [comment]
@Spyromaniac31 Yes so let me try to make it more clear
i actually thought you went for increasing image dimensions intentionally to make the icon inside the tile smaller
![image](https://user-images.githubusercontent.com/20822445/83937164-d232d300-a7ca-11ea-8113-05de463c3ddb.png)
having bigger dimensions should not be a big deal since windows downscales the image anyway the medium is never used at the 150x150 size, but in smaller sizes, mostly 100x100
but then as i tested, when you supply the tile in the 150x150 size, the 100x100 resize that windows makes out of it is slightly better
so i suggested if you actually wanted the icon in the tile to be smaller, a better way of doing that is to use a smaller icon, not increase image dimensions, the assets folder has plenty of sizes that could be used for this
but since as you mentioned, you never intended to increase dimensions, I'm not sure, i don't have any strong opinions on how big the icon inside the tile should be
as a reference, most fluent icons are 32 pixels without including the shadow
![image](https://user-images.githubusercontent.com/20822445/83937416-a31d6100-a7cc-11ea-946b-ae601c119ba3.png)
so adding shadow to the existing icon without any size tweaking should be okay
![image](https://user-images.githubusercontent.com/20822445/83937427-c47e4d00-a7cc-11ea-90e4-16d635367841.png)
@JasonStein if you think this is good, i could use the images from the last upload
> [Assets.zip](https://github.com/JasonStein/Notepads/files/4724803/Assets.zip)

reduce the canvas size to the original sizes then submit a pr

**Comment by JasonStein** [comment]
> @Spyromaniac31 Yes so let me try to make it more clear
> i actually thought you went for increasing image dimensions intentionally to make the icon inside the tile smaller
> ![image](https://user-images.githubusercontent.com/20822445/83937164-d232d300-a7ca-11ea-8113-05de463c3ddb.png)
> having bigger dimensions should not be a big deal since windows downscales the image anyway the medium is never used at the 150x150 size, but in smaller sizes, mostly 100x100
> but then as i tested, when you supply the tile in the 150x150 size, the 100x100 resize that windows makes out of it is slightly better
> so i suggested if you actually wanted the icon in the tile to be smaller, a better way of doing that is to use a smaller icon, not increase image dimensions, the assets folder has plenty of sizes that could be used for this
> but since as you mentioned, you never intended to increase dimensions, I'm not sure, i don't have any strong opinions on how big the icon inside the tile should be
> as a reference, most fluent icons are 32 pixels without including the shadow
> ![image](https://user-images.githubusercontent.com/20822445/83937416-a31d6100-a7cc-11ea-946b-ae601c119ba3.png)
> so adding shadow to the existing icon without any size tweaking should be okay
> ![image](https://user-images.githubusercontent.com/20822445/83937427-c47e4d00-a7cc-11ea-90e4-16d635367841.png)
> @JasonStein if you think this is good, i could use the images from the last upload
> 
> > [Assets.zip](https://github.com/JasonStein/Notepads/files/4724803/Assets.zip)
> 
> reduce the canvas size to the original sizes then submit a pr

Sounds good, go ahead.

**Comment by JasonStein** [comment]
> If someone can colorize this icon with Windows XP's default Luna Blue color scheme, then it would look great IMO. I would have done that (If people like it), but currently, I don't have my desktop with me and my laptop is having scaling issues with adobe apps, so I cannot do that.

I personally don't like that color with current design and there is no point to replicate og notepad in anyway although it is trying to replace it.

**Comment by JasonStein** [comment]
> > If someone can colorize this icon with Windows XP's default Luna Blue color scheme, then it would look great IMO. I would have done that (If people like it), but currently, I don't have my desktop with me and my laptop is having scaling issues with adobe apps, so I cannot do that.
> 
> I personally don't like that color with current design and there is no point to replicate og notepad in anyway although Notepads is trying to replace it.

**Comment by mah-qurashy** [comment]
> If someone can colorize this icon with Windows XP's default Luna Blue color scheme, then it would look great IMO. I would have done that (If people like it), but currently, I don't have my desktop with me and my laptop is having scaling issues with adobe apps, so I cannot do that.

actually we initially considered a blue icon but we decided to stick to the color scheme of the original notepads icon
you can find some variants of that blue icon in the discussion of #171, also i uploaded the PSD file of the icon there, you can always make your own icons and rebuild notepads

**Comment by Spyromaniac31** [comment]
Sounds good. And the icons themselves didn't get resized with the bigger canvas so they should still be pixel perfect. Should I close this issue?

**Comment by JasonStein** [comment]
> Sounds good. And the icons themselves didn't get resized with the bigger canvas so they should still be pixel perfect. Should I close this issue?

I will close it, thanks all for the contribution!
