### ISSUE TITLE
[Bug] Can't close depending on application position

### ISSUE THREAD

**Issue by Kuuchuu** [JasonStein/Notepads#701]
**Describe the bug**
When closing Notepads with an unsaved file open Notepads prompts the user if they would like to save, discard, or cancel. If Notepads is dragged halfway under the taskbar/bottom of the screen and the user attempts to close the application with an unsaved file open it the dialog choices are unselectable, and the user cannot close the application without using task manager or a similar method (You cannot drag the application back into view while the unsaved changes dialog box is open).

**To Reproduce**
Drag Notepads halfway off the bottom of the screen with an unsaved file. Click close button.

**Expected behavior**
Allow user to move application while unsaved changes dialog box is open.

**Screenshots**
![image](https://user-images.githubusercontent.com/20036947/95511755-7f864500-097d-11eb-85bf-15d69e0e5c07.png)

**Desktop:**
 - OS: Windows 10 Pro 2004 19041.508
 - Notepads Version 1.4.2.0

**Comment by XamDR** [comment]
It's possible to drag and move the window if you click on a small area next to the left of the minimize button. This is because, by default UWP apps can't have a fully customized title bar, see a related issue [here](https://github.com/microsoft/microsoft-ui-xaml/issues/1888) On the other hand, I understand that this is not user friendly at all, but this is not a Notepads bug, and instead this happens because a design on the `Content Dialog` control. This control is show modally and currently there isn't a modeless version of it. Again, there is a relevant issue [here](https://github.com/microsoft/microsoft-ui-xaml/issues/2122).

![Demo](https://user-images.githubusercontent.com/35734934/95515475-4ea90e80-0983-11eb-825c-a2110e5bf7cd.gif)
