### ISSUE TITLE
[Bug] Font Weight not Displaying Correctly

### ISSUE THREAD

**Issue by Aurgasm** [JasonStein/Notepads#934]
Font weights for several (but not all) fonts are not displaying correctly.

For example, Arial has 11 different font weights. However, going through the list, they all result in either a condensed or condensed bold weight.

Normal, Thin, Extra Light, Light, Semi Light, Medium all display as a condensed medium.

![image](https://user-images.githubusercontent.com/87892285/126860776-dc8759a5-881e-450e-9735-163baa4610a0.png)

Semi Bold, Bold, Extra Bold, Black, Extra Black all display as a condensed bold.

![image](https://user-images.githubusercontent.com/87892285/126860779-af214072-b89b-41fd-82e4-7508415cfc09.png)

This issue has persisted with some other custom fonts I have tested, which have been purchased separately and installed on windows (UniversSTD)

Small issue, as many other san-serif fonts display properly, but annoying if one is very used to a particular typeface.

**Comment by soumyamahunt** [comment]
Actually Notepads does display font weights properly for "Arial". Notepads shows all the xaml supported font weights and font styles, that doesn't necessarily mean the specific font supports all those font weights/styles. For example if you open font properties in Windows Notepad:

<table><tr><td><img alt="notepad_wnAqyslRkb" src="https://user-images.githubusercontent.com/51203900/128589617-856a3b06-ff7a-4204-b107-4ca7e5a79546.png"></td><td><img alt="notepad_OUxVbBWe0A" src="https://user-images.githubusercontent.com/51203900/128589616-6de74e4c-f28b-4015-8214-993e1b04cb47.png"></td></tr></table>


Arial only supports "Normal" and "Bold" font weight for "Narrow" font stretch type (which XAML detects default font stretch for this font), which is why you are seeing only two font weights when trying to change font weights in Notepads.

**Comment by unforgettableid** [comment]
I don't do much software development anymore nowadays.

I Googled this problem.  It might be a longstanding issue in XAML:  microsoft/microsoft-ui-xaml#808.

A.)  Maybe [this](https://stackoverflow.com/questions/18520188/textbox-fontfamily-ref-new-fontfamilyarial-gives-me-arial-narrow-not-ar#20055134) is a valid workaround?

B.)  Dear @0x7c13.  Even if this Notepads issue is caused by an upstream bug in XAML:  Could we please leave the Notepads issue open until either Microsoft fixes the upstream problem or we find a good workaround?  If we leave the issue open, more people might see it.  We could even label the issue as `help wanted`.
