### ISSUE TITLE
[Bug] Please change  color selected text in dark theme.

### ISSUE THREAD

**Issue by korenevskiy** [JasonStein/Notepads#941]
Please change  color selected text in dark theme.
Using a dark theme. At the same time, having selected the text, it is not visible. With a bright light in the room or with cheap common monitors, the selected text is not visible at all.
And also repair the copying of the selected text.
When copying the selected text, notepad slows down. And sometimes it does not work at all to copy the text, it does not even work by clicking the context menu of the mouse.

**Comment by WolfIcefang** [comment]
I'm 99% sure that Notepads has "Use my Windows accent color" turned on by default, so I recommend changing your Windows Accent Color by going into Windows settings -> Personalization -> Colors -> "Custom color". I recommend changing the color settings globally because (1) File Explorer, and probably other apps, use your accent color for highlighted text, so you'll fix this issue everywhere on your PC at once. (2) The Windows 10 accent color picker automatically warns you when an accent color is going to be too bright or too dark to read.
![image](https://user-images.githubusercontent.com/38160450/135722527-c712b8bb-e146-441f-bbaa-6b4818c6e582.png)

You can also override the default accent color settings in Notepads, by going into Notepads settings -> Personalization -> and disabling the "Use my Windows accent color" switch. You may have already done this, which could be the source of your trouble.
I do think there is a real issue with the app, though - other apps I've used will choose the appropriate text color (white or black) based on the color of the highlighter. Notepads doesn't do this - when text is highlighted, it always turns white. Hopefully an update can come out where it can calculate the correct text color for maximum contrast.

As for copying selected text, I don't know what you're talking about. Truth be told, I've learned not to open really huge files in Notepads just in general, but **if you're having issues copying even small amounts of text**, you might want to mess with the Smart Copy toggle switch and see if that improves anything. I've always kept Smart Copy turned off, so I don't know how well it performs. You can find the setting in Notepads settings -> Advanced -> Smart Copy Settings.
![image](https://user-images.githubusercontent.com/38160450/135722621-f47b497b-0c6f-4418-86f9-d89b4659eb0b.png)

**Comment by korenevskiy** [comment]
> You can find the setting in Notepads settings -> Advanced -> Smart Copy Settings.

Thanks.
But why when using smart copy, I get a hang of the context menu for 5 seconds. For 5 real seconds.
Does it really take a lot of resources to delete spaces?

**Comment by JasonStein** [comment]
> > You can find the setting in Notepads settings -> Advanced -> Smart Copy Settings.
> 
> Thanks. But why when using smart copy, I get a hang of the context menu for 5 seconds. For 5 real seconds. Does it really take a lot of resources to delete spaces? I have a 4 core processor. And copying in notepad with smart copying takes 5 seconds.
> 
> @WolfIcefang
> 
> I have disabled this feature. But copying still takes 5 seconds. Your help is NOT helping.

How large is your file? Can you paste it here for me to play around?

**Comment by korenevskiy** [comment]
Ok.
But. Please add larger contrast for select color for DEFAULT VLAUE
